# Generated by Django 3.0.4 on 2020-03-19 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ID', models.IntegerField(verbose_name='identification_number')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='sex')),
                ('city', models.CharField(max_length=1000, verbose_name='city')),
                ('province', models.CharField(max_length=1000, verbose_name='province')),
                ('country', models.CharField(max_length=1000, verbose_name='country')),
                ('date_onset', models.DateField(verbose_name='date_onset_symptoms')),
                ('date_admission', models.DateField(verbose_name='date_admission_hospital')),
                ('date_confirmation', models.DateField(verbose_name='date_confirmation')),
                ('symptoms', models.CharField(max_length=2000, verbose_name='symptoms')),
                ('travel_dates', models.DateField(verbose_name='travel_history_dates')),
                ('travel_location', models.CharField(max_length=1000, verbose_name='travel_history_location')),
            ],
            options={
                'db_table': 'individuals',
            },
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(verbose_name='serial_number')),
                ('observation_date', models.DateField(verbose_name='observation_date')),
                ('province_state', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('last_update', models.DateTimeField(verbose_name='last_update')),
                ('confirmed', models.BigIntegerField(verbose_name='confirmed_cases')),
                ('deaths', models.BigIntegerField(verbose_name='death_cases')),
                ('recovered', models.BigIntegerField(verbose_name='recovered_cases')),
            ],
            options={
                'db_table': 'totals',
            },
        ),
    ]
