# Generated by Django 3.0.4 on 2020-03-23 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coronavirus_bg', '0001_Individuals_and_Totals_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=1000, verbose_name='twitter_api_user_id')),
                ('tweet_id', models.CharField(max_length=1000, verbose_name='twitter_api_tweet_id')),
                ('datetime', models.DateTimeField(verbose_name='twitter_api_datetime')),
                ('text', models.CharField(max_length=1000, verbose_name='full_tweet_text')),
                ('url', models.CharField(max_length=1000, verbose_name='full_tweet_url')),
                ('total_cases_bg', models.IntegerField(verbose_name='total_cases_infected_bulgaria')),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
