# Generated by Django 3.0.4 on 2020-03-24 23:34

from django.db import migrations, models
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField(verbose_name='observation_date')),
                ('country', models.CharField(max_length=1000)),
                ('serial_number', models.IntegerField(blank=True, null=True, verbose_name='serial_number')),
                ('province_state', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='last_update')),
                ('confirmed', models.BigIntegerField(blank=True, null=True, verbose_name='confirmed_cases')),
                ('deaths', models.BigIntegerField(blank=True, null=True, verbose_name='death_cases')),
                ('recovered', models.BigIntegerField(blank=True, null=True, verbose_name='recovered_cases')),
            ],
            options={
                'unique_together': {('observation_date', 'country')},
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=1000, verbose_name='country')),
                ('date_confirmation', models.DateField(verbose_name='date_confirmation')),
                ('ID', models.IntegerField(blank=True, null=True, verbose_name='identification_number')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='sex')),
                ('city', models.CharField(blank=True, max_length=1000, null=True, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=1000, null=True, verbose_name='province')),
                ('date_onset', models.DateField(blank=True, null=True, verbose_name='date_onset_symptoms')),
                ('date_admission', models.DateField(blank=True, null=True, verbose_name='date_admission_hospital')),
                ('symptoms', models.CharField(blank=True, max_length=2000, null=True, verbose_name='symptoms')),
                ('travel_dates', models.DateField(blank=True, null=True, verbose_name='travel_history_dates')),
                ('travel_location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='travel_history_location')),
            ],
            options={
                'unique_together': {('date_confirmation', 'country')},
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
