# Generated by Django 3.0.4 on 2020-04-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_tweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='total',
            unique_together={('observation_date', 'country', 'province_state')},
        ),
        migrations.RemoveField(
            model_name='total',
            name='serial_number',
        ),
    ]
