# Generated by Django 3.0.4 on 2020-04-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('population', models.PositiveIntegerField()),
                ('first_case', models.DateField(blank=True, null=True)),
                ('first_death', models.DateField(blank=True, null=True)),
                ('emergency_state', models.BooleanField(default=False)),
                ('quarantine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group', models.CharField(choices=[('SD', 'Social distance'), ('BC', 'Business closed'), ('Other', 'Other')], default='Other', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cases', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('recoveries', models.PositiveIntegerField(default=0)),
                ('critical', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'unique_together': {('date', 'country')},
            },
        ),
    ]
