# Generated by Django 3.0.4 on 2020-04-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='cases',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='critical',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='deaths',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='recoveries',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
